import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionWrapper from "./components/SessionWrapper";
import React from "react";
import ChakerWrapper from "./components/ChakraWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <ChakerWrapper>
          <body>{children}</body>
        </ChakerWrapper>
      </html>
    </SessionWrapper>
  );
}
